INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 1, "date", "date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 1, "date", "date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 1, "date", "date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 1, "date", "date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 1, "date", "date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 1, "date", "date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 1, "date", "date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 1, "date", "date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 1, "date", "date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 1, "date", "date");

INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);

INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);