INSERT INTO users (name, age) VALUES ("Emilia", 36);
INSERT INTO users (name, age) VALUES ("Avi", 34);
INSERT INTO users (name, age) VALUES ("Alex", 28);
INSERT INTO users (name, age) VALUES ("Moe", 23);
INSERT INTO users (name, age) VALUES ("Ahura", 32);
INSERT INTO users (name, age) VALUES ("Melanie", 19);
INSERT INTO users (name, age) VALUES ("Chris", 36);
INSERT INTO users (name, age) VALUES ("Joe", 36);
INSERT INTO users (name, age) VALUES ("Brea", 24);
INSERT INTO users (name, age) VALUES ("Tavara", 27);
INSERT INTO users (name, age) VALUES ("Seladon", 33);
INSERT INTO users (name, age) VALUES ("Wonder Woman", 42);
INSERT INTO users (name, age) VALUES ("Captain Planet", 34);
INSERT INTO users (name, age) VALUES ("Jem", 22);
INSERT INTO users (name, age) VALUES ("Carmen Sandiego", 39);
INSERT INTO users (name, age) VALUES ("Iron Man", 35);
INSERT INTO users (name, age) VALUES ("Avati", 31);
INSERT INTO users (name, age) VALUES ("Fernando", 36);
INSERT INTO users (name, age) VALUES ("Filippe", 36);
INSERT INTO users (name, age) VALUES ("Juan", 32);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The DayDream Project", "Creatives", 10000, 2019, 2020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fundraise for Cancer", "Health", 10000, 2019, 2020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Marching Band Funds", "Music", 10000, 2019, 2020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Arts and Cradts Day", "Creatives", 10000, 2019, 2020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Make A Wish", "Health", 10000, 2019, 2020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Locks of Love", "Health", 10000, 2019, 2020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Children Safety", "Wellness", 10000, 2019, 2020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Abused Women Funds", "Assistance", 10000, 2019, 2020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Weight Loss Goals", "Wellness", 10000, 2019, 2020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Homeless Help", "Assistance", 10000, 2019, 2020);

INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 4, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 5, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 8, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 9, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 10, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 11, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 13, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 14, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 15, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 16, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 17, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 18, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 19, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 20, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 2, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 3, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 4, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 5, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 7, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 8, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 9, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 10, 1);
