INSERT INTO users (id, name, age) VALUES (1, "a", 10);
INSERT INTO users (id, name, age) VALUES (2, "b", 11);
INSERT INTO users (id, name, age) VALUES (3, "c", 12);
INSERT INTO users (id, name, age) VALUES (4, "d", 13);
INSERT INTO users (id, name, age) VALUES (5, "e", 14);
INSERT INTO users (id, name, age) VALUES (6, "f", 15);
INSERT INTO users (id, name, age) VALUES (7, "g", 16);
INSERT INTO users (id, name, age) VALUES (8, "h", 17);
INSERT INTO users (id, name, age) VALUES (9, "i", 18);
INSERT INTO users (id, name, age) VALUES (10, "j", 19);
INSERT INTO users (id, name, age) VALUES (11, "k", 20);
INSERT INTO users (id, name, age) VALUES (12, "l", 21);
INSERT INTO users (id, name, age) VALUES (13, "m", 22);
INSERT INTO users (id, name, age) VALUES (14, "n", 23);
INSERT INTO users (id, name, age) VALUES (15, "o", 24);
INSERT INTO users (id, name, age) VALUES (16, "p", 25);
INSERT INTO users (id, name, age) VALUES (17, "q", 26);
INSERT INTO users (id, name, age) VALUES (18, "r", 27);
INSERT INTO users (id, name, age) VALUES (19, "s", 28);
INSERT INTO users (id, name, age) VALUES (20, "t", 29);

INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (1, "aa", "aaa", 100, "September 1st", "OCtober 1st");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (2, "bb", "bbb", 200, "September 2nd", "October 2nd");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (3, "cc", "ccc", 300, "September 3rd", "October 3rd");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (4, "dd", "aaa", 400, "September 4th", "October 4th");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (5, "ee", "bbb", 500, "September 5th", "October 5th");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (6, "ff", "ccc", 600, "September 6th", "October 6th");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (7, "gg", "aaa", 700, "September 7th", "October 7th");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (8, "hh", "bbb", 800, "September 8th", "October 8th");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (9, "ii", "ccc", 900, "September 9th", "October 9th");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (10, "jj", "aaa", 1000, "September 10th", "October 10th");

INSERT INTO pledges (id, amount, user_id, project_id) VALUES (1, 10, 1, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (2, 15, 2, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (3, 20, 3, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (4, 25, 4, 4);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (5, 30, 5, 5);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (6, 35, 6, 6);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (7, 40, 7, 7);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (8, 45, 8, 8);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (9, 50, 9, 9);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (10, 55, 10, 10);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (11, 60, 11, 11);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (12, 65, 12, 12);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (13, 70, 13, 13);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (14, 75, 14, 14);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (15, 80, 15, 15);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (16, 85, 16, 16);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (17, 90, 17, 17);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (18, 95, 18, 18);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (19, 100, 19, 19);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (20, 105, 20, 20);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (21, 110, 21, 21);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (22, 115, 22, 22);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (23, 120, 23, 23);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (24, 125, 24, 24);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (25, 130, 25, 25);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (26, 135, 26, 26);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (27, 140, 27, 27);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (28, 145, 28, 28);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (29, 150, 29, 29);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (30, 155, 30, 30);
